import 'package:flutter/material.dart';

String backgroundSky = "assets/cloud.jpg";
Color? myColor ;
String Mood = "assets/sunny.png";
var dateNow =  DateTime.now() ;
String youm7 = "assets/youm7.png" ;
String dostor = "assets/dostor.jpg" ;
String filgoal = 'assets/filgoal.png' ;
String time = "assets/time-logo-og.png" ;
String masryyoum = "assets/masry-today.jpg" ;
String gamhoria = "assets/gamhoria.jpg" ;
String ahram = "assets/ahramlogoN.png" ;
String wafd = "assets/wafd.jpg" ;
String shrouq = "assets/shrouq.jpg" ;
String ahly = "assets/ahly.jpg" ;
String zamalek = "assets/zamalek.png" ;
String vito = "assets/vito.png" ;
String newtod = "assets/newstod.jpg" ;
String people = "assets/pople.png" ;
String btolat = "assets/btolat.jpg" ;
String skynews = "assets/skynews.png" ;